"""initial 

Revision ID: 2a5184102780
Revises: 6d926edbc67a
Create Date: 2024-02-19 11:59:18.956027

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a5184102780'
down_revision = '6d926edbc67a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shortcuts', sa.Column('code', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shortcuts', 'code')
    # ### end Alembic commands ###
