"""initial 

Revision ID: 6d926edbc67a
Revises: 
Create Date: 2024-02-19 11:47:58.537735

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d926edbc67a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forwarding_clients',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ip_address')
    )
    op.create_table('shortcuts',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('target_link', sa.String(length=255), nullable=False),
    sa.Column('click_count', sa.BigInteger(), nullable=True),
    sa.Column('unique_click_count', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shortcuts_clients',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('shortcut_id', sa.BigInteger(), nullable=False),
    sa.Column('client_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['forwarding_clients.id'], ),
    sa.ForeignKeyConstraint(['shortcut_id'], ['shortcuts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users_shortcuts',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('shortcut_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['shortcut_id'], ['shortcuts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_shortcuts')
    op.drop_table('shortcuts_clients')
    op.drop_table('users')
    op.drop_table('shortcuts')
    op.drop_table('forwarding_clients')
    # ### end Alembic commands ###
